//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jwt.Identity.Framework.Tools.PersianErrorHandelSqlException {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersianSqlExceptionRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersianSqlExceptionRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jwt.Identity.Framework.Tools.PersianErrorHandelSqlException.PersianSqlExceptionRe" +
                            "s", typeof(PersianSqlExceptionRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string _18456 {
            get {
                return ResourceManager.GetString("18456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیتا تکراری است.
        /// </summary>
        public static string _2601 {
            get {
                return ResourceManager.GetString("2601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیتا تکراری است.
        /// </summary>
        public static string _2627 {
            get {
                return ResourceManager.GetString("2627", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایگاه داده معتبر نیست.
        /// </summary>
        public static string _4060 {
            get {
                return ResourceManager.GetString("4060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد با سازنده اتوماتیک مقدار نمی گیرد.
        /// </summary>
        public static string _544 {
            get {
                return ResourceManager.GetString("544", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوانین کلید خارجی رعایت نشده است.
        /// </summary>
        public static string _547 {
            get {
                return ResourceManager.GetString("547", resourceCulture);
            }
        }
    }
}
