//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jwt.Identity.Api.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jwt.Identity.Api.Server.Resources.MessageRes", typeof(MessageRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت کاربر قفل شده است لطفا بعدا تلاش  نمایید.
        /// </summary>
        public static string AccountLucked {
            get {
                return ResourceManager.GetString("AccountLucked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت کاربر تایید نشده است لطفا نسبت به تایید اکانت اقدام فرمایید.
        /// </summary>
        public static string AccountNotConFirm {
            get {
                return ResourceManager.GetString("AccountNotConFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر ارسالی معتبر نمی باشد.
        /// </summary>
        public static string CallBackUrlNotValid {
            get {
                return ResourceManager.GetString("CallBackUrlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلایت معتبر ندارد.
        /// </summary>
        public static string ClientNoExist {
            get {
                return ResourceManager.GetString("ClientNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارسالی منقضی شده است لطفا کد جدید دریافت کنید.
        /// </summary>
        public static string CodeExpire {
            get {
                return ResourceManager.GetString("CodeExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوکی تنظیم گردید.
        /// </summary>
        public static string CookiesSet {
            get {
                return ResourceManager.GetString("CookiesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلاینت قبلا ثبت شده است.
        /// </summary>
        public static string DouplicateClient {
            get {
                return ResourceManager.GetString("DouplicateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل ارسال گردید.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن وارد شده معتبر نمی باشد.
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل تایید شد.
        /// </summary>
        public static string MobileConfirmed {
            get {
                return ResourceManager.GetString("MobileConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود با تامین کننده خارجی پیکربندی نشده است.
        /// </summary>
        public static string NotExistExternalProvider {
            get {
                return ResourceManager.GetString("NotExistExternalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provider معتبر نیست.
        /// </summary>
        public static string NotValidProvider {
            get {
                return ResourceManager.GetString("NotValidProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده صحیح است.
        /// </summary>
        public static string OKTotpInput {
            get {
                return ResourceManager.GetString("OKTotpInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set session first.
        /// </summary>
        public static string SessionIdNotSet {
            get {
                return ResourceManager.GetString("SessionIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید ارسال گردید.
        /// </summary>
        public static string TotpSent {
            get {
                return ResourceManager.GetString("TotpSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorize.
        /// </summary>
        public static string Unauthorize {
            get {
                return ResourceManager.GetString("Unauthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی پیش آمده مجدد درخواست کد نمایید.
        /// </summary>
        public static string UnknownTotpError {
            get {
                return ResourceManager.GetString("UnknownTotpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی پیش آمده لطفا مجدد اقدام نام نمایید.
        /// </summary>
        public static string UnkonwnError {
            get {
                return ResourceManager.GetString("UnkonwnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر با موفقیت ساخته شد.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر با موفقیت وارد شد.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع لاگین معتبر نیست.
        /// </summary>
        public static string WrongLoginType {
            get {
                return ResourceManager.GetString("WrongLoginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده صحیح نمی باشد.
        /// </summary>
        public static string WrongTotpInput {
            get {
                return ResourceManager.GetString("WrongTotpInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string WrongUserOrPass {
            get {
                return ResourceManager.GetString("WrongUserOrPass", resourceCulture);
            }
        }
    }
}
